#!/usr/bin/env bash
# Write a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when
# receiving a SIGQUIT or SIGTERM signal
trap "echo I hate the kill command ; rm /var/run/myscript.pid ; exit" SIGTERM SIGQUIT
trap "echo Y U no love me?! ; exit" SIGINT

pidof bash >> /var/run/myscript.pid
while ((1)); do
    echo "To infinity and beyond"
    sleep 2
done
